---
name: Jekyll CI
permissions: {}

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  call-jekyll-build:
    uses: ./.github/workflows/jekyll-build.yml
    permissions:
      contents: read
    secrets:
      GH_BOT_EMAIL: ${{ secrets.GH_BOT_EMAIL }}
      GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
    with:
      clean_gh_pages: true
      gh_bot_name: ${{ vars.GH_BOT_NAME }}
      target_branch: gh-pages
